DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS board;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS board_member;
DROP TABLE IF EXISTS task_executor;

CREATE TABLE user (
  id TEXT PRIMARY KEY NOT NULL,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  password TEXT NOT NULL,
  registered TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
  info TEXT DEFAULT '' NOT NULL
);

CREATE TABLE board (
  id TEXT PRIMARY KEY NOT NULL,
  owner_id TEXT NOT NULL,
  name TEXT NOT NULL,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (owner_id)
    REFERENCES user (id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);

CREATE TABLE task (
  id TEXT PRIMARY KEY NOT NULL,
  board_id TEXT NOT NULL,
  created TEXT DEFAULT CURRENT_TIMESTAMP NOT NULL,
  status TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  FOREIGN KEY (board_id)
    REFERENCES board (id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);
